const show = [
    {
        id:1,
        title: "How I Met Your Mother",
        img: 'https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/2970945770FC137FF7D5D3408D5D40836FD4C715DE6A1744F6F5AF21B2386827/scale?width=1200&aspectRatio=1.78&format=webp',
        description: "How I Met Your Mother is a sitcom that follows Ted Mosby, who recounts to his children the events leading up to his meeting their mother. Set in New York City, the series chronicles Ted's adventures with his close-knit group of friends: the suave Barney Stinson, the sweet but naive Marshall Eriksen, Marshall’s wife and artist Lily Aldrin, and the independent, career-focused Robin Scherbatsky. The narrative, full of humor and heart, spans nine seasons, blending Ted's romantic pursuits and career aspirations with the group's evolving dynamics. The story concludes with the long-awaited reveal of the mother and the fate of Ted’s relationships",
        rating: "⭐⭐⭐⭐⭐",
    },
    {
        id:2,
        title: "Justice League: Animated Series",
        img: '',
        description: "",
        rating: "",
    },
    {
        id:3,
        title: "Chuck",
        img: '',
        description: "",
        rating: "",
    },
    {
        id:4,
        title: "White Collar",
        img: '',
        description: "",
        rating: "",
    },
    {
        id:5,
        title: "Friends",
        img: '',
        description: "",
        rating: "",
    },
    {
        id:6,
        title: "Community",
        img: '',
        description: "",
        rating: "",
    },
    {
        id:7,
        title: "The Flash",
        img: '',
        description: "",
        rating: "",
    },
    {
        id:8,
        title: "Married With Children",
        img: '',
        description: "",
        rating: "",
    },
    {
        id:9,
        title: "My Name is Earl",
        img: '',
        description: "",
        rating: "",
    },
    {
        id:10,
        title: "Family Guy",
        img: '',
        description: "",
        rating: "",
    },
    {
        id:11,
        title: "The Simpsons",
        img: '',
        description: "",
        rating: "",
    },
    {
        id:12,
        title: "Futurama",
        img: '',
        description: "",
        rating: "",
    },
    {
        id:13,
        title: "South Park",
        img: '',
        description: "",
        rating: "",
    },
    {
        id:14,
        title: "Gossip Girl",
        img: '',
        description: "",
        rating: "",
    },
    {
        id:15,
        title: "Suits",
        img: '',
        description: "",
        rating: "",
    },
    {
        id:16,
        title: "The Mentalist",
        img: '',
        description: "",
        rating: "",
    },
    {
        id:17,
        title: "Brooklyn Nine Nine",
        img: '',
        description: "",
        rating: "",
    },
    {
        id:18,
        title: "Batman: Animated Series",
        img: '',
        description: "",
        rating: "",
    },
]

export default show
