const show = [
    {
        id:1,
        title: "How I Met Your Mother",
        img: 'https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/2970945770FC137FF7D5D3408D5D40836FD4C715DE6A1744F6F5AF21B2386827/scale?width=1200&aspectRatio=1.78&format=webp',
        description: "How I Met Your Mother is a sitcom that follows Ted Mosby, who recounts to his children the events leading up to his meeting their mother. Set in New York City, the series chronicles Ted's adventures with his close-knit group of friends: the suave Barney Stinson, the sweet but naive Marshall Eriksen, Marshall’s wife and artist Lily Aldrin, and the independent, career-focused Robin Scherbatsky. The narrative, full of humor and heart, spans nine seasons, blending Ted's romantic pursuits and career aspirations with the group's evolving dynamics. The story concludes with the long-awaited reveal of the mother and the fate of Ted’s relationships",
        rating: "⭐⭐⭐⭐⭐",
    },
    {
        id:2,
        title: "Justice League",
        img: 'https://miro.medium.com/v2/resize:fit:1024/1*U5_PnrRl0emEOQh3Qbm_FQ.jpeg',
        description: "Justice League is an acclaimed animated series that aired from 2001 to 2004 on Cartoon Network. It follows DC Comics' iconic superheroes - Batman, Superman, Wonder Woman, Flash, Green Lantern, Hawkgirl, and Martian Manhunter - as they unite to face global threats. The show is praised for its mature storytelling, character development, and high-quality animation. It features complex plots, moral dilemmas, and political themes while respecting each character's depth. Justice League is considered one of the best animated superhero series, setting a new standard for the genre",
        rating: "⭐⭐⭐⭐⭐",
    },
    {
        id:3,
        title: "Chuck",
        img: 'https://m.media-amazon.com/images/S/pv-target-images/f7262d02d0f61cf015490bd7d23261682e7d3b9fb8bfc850c7482dbf369b8091.jpg',
        description: "Chuck is a comedy-action series that aired from 2007 to 2012, following Chuck Bartowski, an ordinary computer technician who accidentally receives government secrets embedded in his brain. The show blends spy thriller elements with workplace comedy as Chuck navigates his new double life. Alongside CIA agent Sarah Walker and NSA agent John Casey, Chuck uses his newfound abilities to help national security. The series is praised for its witty dialogue, engaging storylines, and the chemistry between its cast members, particularly Zachary Levi as Chuck and Yvonne Strahovski as Sarah",
        rating: "⭐⭐⭐⭐⭐",
    },
    {
        id:4,
        title: "White Collar",
        img: 'https://dnm.nflximg.net/api/v6/2DuQlx0fM4wd1nzqm5BFBi6ILa8/AAAAQYQVrXKPQPV_2nIRH1yw0pzKDJxJHhKHjhpIheV8f-4pn70IE_bhCgekTUwL_oqX0KNhjGr7hYooFa5s0s1KYdBIuIeZFaTIJM-N_xFfxSP6vzav4Tvs-tDE5cHhSdM4XshLuEvgjDCjEagfj844tCJd.jpg?r=44c',
        description: "White Collar is a crime drama series that aired from 2009 to 2014. It centers on Neal Caffrey, a charming and brilliant con artist, who strikes a deal with FBI agent Peter Burke to avoid prison. Neal becomes a consultant for the FBI's white-collar crime division, using his criminal expertise to catch other lawbreakers. The show explores the dynamic relationship between Neal and Peter, blending clever heists, intricate cons, and character-driven storylines. White Collar is known for its witty dialogue, stylish aesthetics, and the charismatic performance of Matt Bomer as Neal Caffrey.",
        rating: "⭐⭐⭐⭐⭐",
    },
    {
        id:5,
        title: "Friends",
        img: 'https://m.media-amazon.com/images/S/pv-target-images/c7fc75a423fc33698265a27fe446a41026f3c8642fd6c8706c43b897d2ffb3e6.jpg',
        description: "Friends is an iconic sitcom that aired from 1994 to 2004, following six young adults navigating life, love, and careers in New York City. The ensemble cast - Rachel, Monica, Phoebe, Joey, Chandler, and Ross - became cultural touchstones, known for their distinct personalities and interpersonal dynamics. The show's witty dialogue, relatable situations, and emotional moments resonated with audiences worldwide. Friends tackled various themes, from romantic relationships to career struggles, all while maintaining its signature humor. Its enduring popularity has cemented its place in television history.",
        rating: "⭐⭐⭐⭐",
    },
    {
        id:6,
        title: "Community",
        img: 'https://m.media-amazon.com/images/S/pv-target-images/d6e25ce8c6cdf788ec947effcec7854aee7090812cb73e536adf6b75b9eb7ca6.jpg',
        description: "Community is a comedy series that aired from 2009 to 2015, set at the fictional Greendale Community College. It follows a study group of misfits led by Jeff Winger, a disbarred lawyer. Known for its meta-humor, pop culture references, and genre-bending episodes, Community subverts sitcom tropes while exploring themes of friendship and personal growth. Creator Dan Harmon's unique style, coupled with the ensemble cast's chemistry, garnered a devoted fanbase. Despite facing cancellation challenges, the show's creativity and six seasons and a movie mantra exemplify its resilient spirit.",
        rating: "⭐⭐⭐⭐",
    },
    {
        id:7,
        title: "The Flash",
        img: 'https://ntvb.tmsimg.com/assets/p10781465_b_h8_ay.jpg?w=960&h=540',
        description: "The Flash is a superhero TV series based on the DC Comics character Barry Allen. Debuting in 2014, it follows forensic scientist Barry who gains super-speed after a particle accelerator explosion. As the Flash, he protects Central City from metahuman threats and other dangers. The show blends action, drama, and science fiction, exploring themes of time travel, parallel universes, and the consequences of altering the past. Known for its likable characters, emotional depth, and complex storylines, The Flash has become a cornerstone of the Arrowverse.",
        rating: "⭐⭐⭐⭐",
    },
    {
        id:8,
        title: "Married With Children",
        img: 'https://ntvb.tmsimg.com/assets/p7896466_b_h10_aa.jpg?w=1280&h=720',
        description: "Married with Children is a groundbreaking sitcom that aired from 1987 to 1997. It centers on the Bundy family, led by misanthropic shoe salesman Al Bundy and his lazy, shopping-addicted wife Peggy. Their children, promiscuous daughter Kelly and awkward son Bud, round out the dysfunctional family. The show is known for its crude humor, sarcastic wit, and deliberate subversion of the idealized family sitcom format. Married with Children pushed boundaries with its politically incorrect jokes and unconventional portrayal of family life, becoming a cult classic in the process.",
        rating: "⭐⭐⭐",
    },
    {
        id:9,
        title: "My Name is Earl",
        img: 'https://resizing.flixster.com/gJmSbXSi9U3Ej318TuNFBkOy1gw=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p185093_b_h9_aa.jpg',
        description: "My Name is Earl is a comedy series that aired from 2005 to 2009. It follows Earl Hickey, a petty criminal who has an epiphany after winning the lottery and being hit by a car. Believing in karma, Earl creates a list of his past misdeeds and sets out to make amends for each one. The show combines humor with heartwarming moments as Earl, aided by his dimwitted brother Randy and ex-wife Joy, attempts to become a better person. Set in a quirky small town, My Name is Earl explores themes of redemption and personal growth with a unique blend of comedy and sincerity.",
        rating: "⭐⭐⭐⭐",
    },
    {
        id:10,
        title: "Family Guy",
        img: 'https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/7238583A12BC3EE570A6D8E240D67D0E6CACE9C782B434F7FFE09747512BDE0C/scale?width=1200&aspectRatio=1.78&format=webp',
        description: "Family Guy is an animated sitcom created by Seth MacFarlane that debuted in 1999. It follows the dysfunctional Griffin family in the fictional town of Quahog, Rhode Island. The show is known for its irreverent humor, cutaway gags, and pop culture references. Centered around bumbling father Peter, his wife Lois, children Meg, Chris, and Stewie, and their talking dog Brian, Family Guy tackles controversial subjects with crude humor and social commentary. Despite facing cancellation, the series has maintained a dedicated fanbase and continues to air new episodes.",
        rating: "⭐⭐⭐⭐⭐",
    },
    {
        id:11,
        title: "The Simpsons",
        img: 'https://lumiere-a.akamaihd.net/v1/images/simpsons_s33_social_16x9_1920x1080_en_v1_xxxxxx_395a8f3b.png?region=0,0,1920,1080&width=960',
        description: "The Simpsons is an iconic animated sitcom that has been on air since 1989. It follows the dysfunctional Simpson family in the fictional town of Springfield. Known for its satirical take on American culture, politics, and society, the show has introduced numerous catchphrases and cultural references that have become part of everyday language. With its sharp wit, memorable characters, and ability to tackle contemporary issues, The Simpsons has left an indelible mark on popular culture, influencing generations of viewers and shaping the landscape of animated television.",
        rating: "⭐⭐⭐⭐",
    },
    {
        id:12,
        title: "Futurama",
        img: 'https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/47FCE4F29DC1D7C1FC72071B226D58E2FC345B4C258E88683E5250F7A4BA96B4/scale?width=1200&amp;aspectRatio=1.78&amp;format=webp',
        description: "Futurama is a science fiction animated comedy created by Matt Groening, which originally aired from 1999 to 2003 and was later revived. Set in the year 3000, it follows Philip J. Fry, a pizza delivery boy accidentally cryogenically frozen and thawed out in the future. The show cleverly blends sci-fi concepts with sharp humor and social commentary. Known for its intelligent writing, complex storylines, and lovable characters like the robot Bender, Futurama has garnered a dedicated fanbase and critical acclaim for its unique blend of humor and futuristic storytelling.",
        rating: "⭐⭐⭐⭐",
    },
    {
        id:13,
        title: "South Park",
        img: 'https://variety.com/wp-content/uploads/2021/04/South-Park-Key-Art-2.jpg?w=1024',
        description: "South Park is an animated sitcom known for its crude humor, satirical take on current events, and controversial subject matter. Created by Trey Parker and Matt Stone, the show follows the adventures of four elementary school boys in the fictional Colorado town of South Park. It has gained notoriety for its unfiltered approach to sensitive topics, often pushing the boundaries of acceptable content on television. South Park's rapid production schedule allows it to respond quickly to current events, making it a relevant and often polarizing voice in popular culture and social commentary.",
        rating: "⭐⭐⭐⭐⭐",
    },
    {
        id:14,
        title: "Gossip Girl",
        img: 'https://static1.cbrimages.com/wordpress/wp-content/uploads/2021/01/0-YlpLIprIwr-iJezA-1.jpg',
        description: "Gossip Girl is a teen drama series that aired from 2007 to 2012, following the lives of privileged upper-class adolescents in Manhattan's Upper East Side. The show revolves around the anonymous blogger Gossip Girl, who narrates and exposes the scandals of the main characters. Centered on the complex relationships and rivalries between Serena van der Woodsen, Blair Waldorf, Chuck Bass, and Dan Humphrey, the series explores themes of wealth, power, and social status. Known for its fashion, drama, and controversial storylines, Gossip Girl became a cultural phenomenon and launched the careers of its young cast.",
        rating: "⭐⭐⭐⭐",
    },
    {
        id:15,
        title: "Suits",
        img: 'https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2024%2F02%2Fnbcuniversal-suits-la-tv-show-spinoff-in-progress-announcement-001.jpg?cbr=1&q=90',
        description: "Suits is a legal drama series that aired from 2011 to 2019. It follows Mike Ross, a brilliant college dropout who lands a job as an associate at a prestigious New York law firm despite lacking a law degree. Working alongside Harvey Specter, a charismatic and ruthless senior partner, Mike must navigate high-stakes cases while keeping his secret. The show is known for its sharp dialogue, complex legal plots, and the dynamic relationship between Mike and Harvey. Suits explores themes of loyalty, ethics, and ambition in the cutthroat world of corporate law.",
        rating: "⭐⭐⭐⭐",
    },
    {
        id:16,
        title: "The Mentalist",
        img: 'https://ntvb.tmsimg.com/assets/p7894648_b_h10_ae.jpg?w=1280&h=720',
        description: "The Mentalist is a crime drama series that aired from 2008 to 2015. It centers on Patrick Jane, a former psychic who uses his keen observational skills to assist the California Bureau of Investigation in solving crimes. Haunted by the murder of his wife and daughter by the serial killer Red John, Jane joins the CBI to seek revenge. The show combines elements of mystery, psychological manipulation, and character-driven storytelling. Simon Baker's charismatic performance as Jane, along with the show's clever plots and ongoing Red John storyline, made The Mentalist a popular and engaging series.",
        rating: "⭐⭐⭐⭐",
    },
    {
        id:17,
        title: "Brooklyn Nine Nine",
        img: 'https://media.licdn.com/dms/image/C5612AQG5EMSO1ktfnA/article-cover_image-shrink_600_2000/0/1633088679225?e=2147483647&v=beta&t=RWYZNpwKCh7ZSfPNNVBdiOsTnmRVrUtprUVtFiRQFvY',
        description: "Brooklyn Nine-Nine is a police sitcom that aired from 2013 to 2021. Set in Brooklyn's fictional 99th precinct, the show follows a team of detectives led by the immature but talented Jake Peralta and the strict, by-the-book Captain Raymond Holt. Known for its diverse cast, witty humor, and heartfelt moments, Brooklyn Nine-Nine balances comedic police work with character development and social issues. The series gained critical acclaim for its inclusive representation, clever writing, and the ensemble cast's chemistry, becoming a beloved comedy that tackles serious topics with sensitivity and humor.",
        rating: "⭐⭐⭐",
    },
    {
        id:18,
        title: "Batman: Animated Series",
        img: 'https://wallpapers.com/images/hd/batman-animated-tprs3fi0g3u9rwgs.jpg',
        description: "Batman: The Animated Series is a groundbreaking animated show that aired from 1992 to 1995. Set in a film noir-inspired Gotham City, it follows Batman as he fights crime and confronts iconic villains. The series is acclaimed for its sophisticated storytelling, complex characters, and dark, atmospheric art style. It redefined superhero animation with its mature themes and psychological depth. Batman: The Animated Series introduced new characters like Harley Quinn and reinvented classic villains, leaving a lasting impact on Batman lore and setting a new standard for animated superhero shows.",
        rating: "⭐⭐⭐⭐⭐",
    },
]

export default show
